# main text of home
name: Sam Nunnally
bio: |+
  I am a technologist with 18 years of professional and technical experience in the Technology industry. Currently my focus is Enterprise Architecture, Automation, DevOps and Cloud. I excel at designing and implementing scalable solutions using core principles, standards and design patterns such as Event Driven Architecture, Web APIs, Security, Service Oriented Architecture, Cloud, Web and Mobility.<br/>
  <b>Guiding Principles</b><br/>
  Lead by Example<br/>
  Separation of Concerns<br/>
  Principle of Least Astonishment<br/>
  Murphy's Law<br/>
  Occam's Razor<br/>
  Don't repeat yourself<br/>


# twitter summary info
description: A blog about technology

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

url: https://samnunnally.github.io/
# your url: http://USERNAME.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
analytics-google: 'UA-89118579-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
disqus: mydisqus

# if you don't have any of social below, comment the line
facebook: samnunnally42
twitter: SamNunnally42
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: samnunnally
youtube: channel/UCV7p-WmzdBLvaSy3LDlGUJw
spotify: samnunnally
github: samnunnally
stackoverflow: 2958091/sam-nunnally
quora: Sam-Nunnally
reddit: samnunnally
#medium: medium
#vimeo: myvimeo
email: sam@samnunnally.com

authors:
    johndoe:
        name: John Doe
        bio: A Man who travels the world eating noodles
        external-image: false
        picture: assets/images/profile.jpg
        twitter: johndoe
    jamesfoster:
        name: James Foster
        bio: A Man who develops software with coffee
        external-image: false
        picture: assets/images/james.jpg
        twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
# projects: true

# if you don't need "about" or "blog", comment them out below
about: false
blog: false

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# show next & prev links in blog post?
blog-nav-links: false

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

sass:
    sass_dir: _sass
    style: :compressed

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
