# main text of home
name: Sam Nunnally
bio: |+
  <div style="text-align: left;">
  I am a technologist with over 20 years of professional experience in the Technology and Software Development industry; 18 years of that time in the railroad industry. Currently my focus is Enterprise Architecture, Cloud, Domain-Driven Design and DevOps. I excel at designing and implementing solutions that scale and evolve using core principles, standards and design patterns such as Event Driven Architecture, Web APIs, Security, Domain-Driven Design, Cloud, Web and Mobility.
  </div>
  <br/>
  <b>Guiding Principles</b><br/>
  Lead by Example<br/>
  Separation of Concerns<br/>
  Principle of Least Astonishment<br/>
  Murphy's Law<br/>
  Occam's Razor<br/>
  Don't repeat yourself<br/>


# twitter summary info
description: A blog about technology

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

url: https://samnunnally.github.io/
# your url: http://USERNAME.github.io
# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
# resume-external: true
resume-url: /resume

url: https://samnunnally.github.io/
# your url: https://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-89118579-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
facebook: samnunnally42
twitter: SamNunnally42
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: samnunnally
youtube: channel/UCV7p-WmzdBLvaSy3LDlGUJw
spotify: samnunnally
github: samnunnally
stackoverflow: 2958091/sam-nunnally
quora: Sam-Nunnally
reddit: samnunnally
#medium: medium
#vimeo: myvimeo
email: sam@samnunnally.com
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# gitlab: mygitlab
# lastfm: mylastfm
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd


# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: false
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended

# if you don't need projects, comment the *projects* configs below
# projects: true

# if you don't need "about" or "blog", comment them out below
about: false
blog: false

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

# seo
title: Sam Nunnally
author: Sam Nunnally

sass:
    sass_dir: _sass
    style: :compressed

plugins:
  - jemoji
  - jekyll-mentions
# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "travis.sh",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "node_modules",
    "vendor",
  ]
